#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require "bot_twooper"

if ARGV.include? "--update-sde"
  result = BotTwooper::SDE::Updater.new.execute
  exit(result)
end
