#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'bot_twooper'

if ARGV.include? '--update-sde'
  result = BotTwooper::SDEUpdater.new.execute
  exit(result)
end

if ARGV.size != 2
  puts "Usage: bot_twooper <jid> <password>"
  exit
end

puts "Starting bot_twooper"
puts "\n"

client = BotTwooper::Client.new(rooms: ['testingbots@conference.psychotic-tendencies.net', 'testingbots2@conference.psychotic-tendencies.net'], nick: 'bot_twooper')
client.setup ARGV[0], ARGV[1]
EM.run { client.run }
